spring:
  profiles: docker
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: 'jdbc:postgresql://postgres:5432/postgresDB'
    driver-class-name: org.postgresql.Driver
    username: postgresUser
    password: postgresPassword
    continueOnError: true
    initialize: false
logging:
    config: 'classpath:logback.xml'
    level:
      com.icontrol: 'DEBUG'
      org.springframework.web: 'DEBUG'
      org.hibernate.SQL: 'DEBUG'
